name: main
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.19'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o sup -trimpath -ldflags "-s -w -X 'github.com/sequix/sup/pkg/buildinfo.Commit=$(git rev-parse HEAD)'" cmd/main.go

      - name: Compress Binary
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v3.96
          files: |
            ./sup
          args: --best -f

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sup-nightly
          path: ./sup

#      - name: Test
#        run: |
#          go test -v ./... -coverprofile=coverage.txt -covermode=atomic
#          go test -v ./... -race

#      - name: Publish coverage
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.txt
